FROM genepattern/tfsites:15.5.1

COPY tfsites-webportal /build/tfsites-webportal 


RUN chmod a+x /build/tfsites-webportal/*.sh
#RUN apt-get install vim --yes

# to get the courier new font
RUN apt-get update && apt-get install -y fonts-dejavu-core


RUN pip install seaborn
RUN pip install markdown psutil jinja2
RUN pip install numpy==1.26.4

# PITA attempt to install courier font
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get clean && \
    apt-get install -y --no-install-recommends software-properties-common && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
RUN    sed -i 's/main/main contrib non-free/' /etc/apt/sources.list 
RUN    apt install ttf-mscorefonts-installer -y   

RUN    rm ~/.cache/matplotlib -rf 
RUN    python3 -c "import matplotlib.font_manager; matplotlib.font_manager._load_fontmanager()" 




#COPY maxit-v8.120-prod-bin-linux.tar.gz  /build/maxit-v8.120-prod-bin-linux.tar.gz 
#RUN cd /build && \
#     zcat maxit-v8.120-prod-bin-linux.tar.gz | tar -xf - && \
#     export RCSBROOT=/build/maxit-v8.120-prod-bin-linux && \
#     export PATH=$RCSBROOT/bin:$PATH  && \
#     cd /build/maxit-v8.120-prod-bin-linux/etc && \
#     ./binary.sh  



